name: UncannyGallery
description: A browser for the images in the UncannyCamera app.

dependency_overrides:
  dart_config:
    git:
      url: https://github.com/SPodjasek/dart_config.git
      ref: fix_dart21

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.3.1
  image: ^2.0.4
  http: ^0.11.3
  google_sign_in: ^3.0.5
  firebase_auth: ^0.5.19
  firebase_database: ^1.0.4
  path_provider: ^0.4.1
  flutter_launcher_icons: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
