name: UncannyGallery
description: A browser for the images in the UncannyCamera app.

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.3.1
  image: ^2.0.4
  http: ^0.11.3
  google_sign_in: ^3.0.5
  firebase_auth: ^0.5.19
  firebase_database: ^1.0.4
  path_provider: ^0.4.1

flutter:
  uses-material-design: true

